
name: Release

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    # needs: [linux, windows, macos, macos-m1, linux-arm64]
    needs: [linux, windows, macos, macos-m1]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/download-artifact@v3

      - run: |
          VER="${{ github.ref }}"
          echo "VERSION=${VER#refs/tags/v}" >> $GITHUB_ENV

      - name: Archive Linux Library
        run: zip --junk-paths libgpu-setup-linux-${{ env.VERSION }}.zip linux/*
      - name: Archive Windows Library
        run: zip --junk-paths libgpu-setup-windows-${{ env.VERSION }}.zip windows/*
      - name: Archive MacOS Library
        run: zip --junk-paths libgpu-setup-macos-${{ env.VERSION }}.zip macos/*
      - name: Archive MacOS-M1 Library
        run: zip --junk-paths libgpu-setup-macos-m1-${{ env.VERSION }}.zip macos-m1/*
      # - name: Archive Linux ARM64 Library
      #   run: zip --junk-paths libgpu-setup-linux-arm64-${{ env.VERSION }}.zip linux-arm64/*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ env.VERSION }}
          files: |
            libgpu-setup-linux-${{ env.VERSION }}.zip
            libgpu-setup-windows-${{ env.VERSION }}.zip
            libgpu-setup-macos-${{ env.VERSION }}.zip
            libgpu-setup-macos-m1-${{ env.VERSION }}.zip
          #  libgpu-setup-linux-arm64-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
